### ISSUE TITLE
`get-exact-matches` function on cli need to be ran on root folder or table-linker

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/table-linker#1]
If run on any other arbitary folder, the program will raise an error saying it can't file the `phrase_query.json` file as:
```
(gpt2) ➜  iswc_challenge_data tl --url http://kg2018a.isi.edu:9200 --index wiki_labels_aliases_1 clean -c label ./round4/canonical/v15_562.csv / get-exact-matches -c label_clean
Command: get-exact-matches
Error Message:  Traceback (most recent call last):
  File "/Users/minazuki/Desktop/studies/master/2018Summer/DSBOX_2019/table-linker/tl/candidate_generation/es_search.py", line 13, in __init__
    self.query = json.load(open('tl/candidate_generation/phrase_query.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'tl/candidate_generation/phrase_query.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/minazuki/Desktop/studies/master/2018Summer/DSBOX_2019/table-linker/tl/cli/get-exact-matches.py", line 42, in run
    es_pass=kwargs['password'])
  File "/Users/minazuki/Desktop/studies/master/2018Summer/DSBOX_2019/table-linker/tl/candidate_generation/get_exact_matches.py", line 9, in __init__
    self.es = Search(es_url, es_index, es_user=es_user, es_pass=es_pass)
  File "/Users/minazuki/Desktop/studies/master/2018Summer/DSBOX_2019/table-linker/tl/candidate_generation/es_search.py", line 15, in __init__
    self.query = json.load(open('./phrase_query.json'))
FileNotFoundError: [Errno 2] No such file or directory: './phrase_query.json'
```

**Comment by saggu** [comment]
@ckxz105 I have fixed this in the latest commit. Please test

**Comment by ckxz105** [comment]
seems its ok now
